<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GcGhPaM' shared service.

return $this->privates['.service_locator.GcGhPaM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'offreRepository' => ['privates', 'App\\Repository\\OffreRepository', 'getOffreRepositoryService.php', true],
], [
    'offreRepository' => 'App\\Repository\\OffreRepository',
]);
