<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.h3jh2b7' shared service.

return $this->privates['.service_locator.h3jh2b7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'offre' => ['privates', '.errored..service_locator.h3jh2b7.App\\Entity\\Offre', NULL, 'Cannot autowire service ".service_locator.h3jh2b7": it references class "App\\Entity\\Offre" but no such service exists.'],
], [
    'offre' => 'App\\Entity\\Offre',
]);
