<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LE8uUJJ' shared service.

return $this->privates['.service_locator.LE8uUJJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController\\OffreController::delete' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\OffreController::edit' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\OffreController::index' => ['privates', '.service_locator.GcGhPaM', 'get_ServiceLocator_GcGhPaMService.php', true],
    'App\\Controller\\AdminController\\OffreController::show' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\RegionController::delete' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController::edit' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController::index' => ['privates', '.service_locator.BPeAJFx', 'get_ServiceLocator_BPeAJFxService.php', true],
    'App\\Controller\\AdminController\\RegionController::show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\OffreController:delete' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\OffreController:edit' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\OffreController:index' => ['privates', '.service_locator.GcGhPaM', 'get_ServiceLocator_GcGhPaMService.php', true],
    'App\\Controller\\AdminController\\OffreController:show' => ['privates', '.service_locator.h3jh2b7', 'get_ServiceLocator_H3jh2b7Service.php', true],
    'App\\Controller\\AdminController\\RegionController:delete' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController:edit' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController:index' => ['privates', '.service_locator.BPeAJFx', 'get_ServiceLocator_BPeAJFxService.php', true],
    'App\\Controller\\AdminController\\RegionController:show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
], [
    'App\\Controller\\AdminController\\OffreController::delete' => '?',
    'App\\Controller\\AdminController\\OffreController::edit' => '?',
    'App\\Controller\\AdminController\\OffreController::index' => '?',
    'App\\Controller\\AdminController\\OffreController::show' => '?',
    'App\\Controller\\AdminController\\RegionController::delete' => '?',
    'App\\Controller\\AdminController\\RegionController::edit' => '?',
    'App\\Controller\\AdminController\\RegionController::index' => '?',
    'App\\Controller\\AdminController\\RegionController::show' => '?',
    'App\\Controller\\AdminController\\OffreController:delete' => '?',
    'App\\Controller\\AdminController\\OffreController:edit' => '?',
    'App\\Controller\\AdminController\\OffreController:index' => '?',
    'App\\Controller\\AdminController\\OffreController:show' => '?',
    'App\\Controller\\AdminController\\RegionController:delete' => '?',
    'App\\Controller\\AdminController\\RegionController:edit' => '?',
    'App\\Controller\\AdminController\\RegionController:index' => '?',
    'App\\Controller\\AdminController\\RegionController:show' => '?',
]);
