<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.h3jh2b7.App\Entity\Offre' shared service.

include_once $this->targetDirs[3].'/src/Entity/Offre.php';

return $this->privates['.errored..service_locator.h3jh2b7.App\\Entity\\Offre'] = new \App\Entity\Offre();
