<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XDZQo9y' shared service.

return $this->privates['.service_locator.XDZQo9y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController\\RegionController::delete' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController::edit' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController::index' => ['privates', '.service_locator.BPeAJFx', 'get_ServiceLocator_BPeAJFxService.php', true],
    'App\\Controller\\AdminController\\RegionController::show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController:delete' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController:edit' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
    'App\\Controller\\AdminController\\RegionController:index' => ['privates', '.service_locator.BPeAJFx', 'get_ServiceLocator_BPeAJFxService.php', true],
    'App\\Controller\\AdminController\\RegionController:show' => ['privates', '.service_locator.vIHt.Cx', 'get_ServiceLocator_VIHt_CxService.php', true],
], [
    'App\\Controller\\AdminController\\RegionController::delete' => '?',
    'App\\Controller\\AdminController\\RegionController::edit' => '?',
    'App\\Controller\\AdminController\\RegionController::index' => '?',
    'App\\Controller\\AdminController\\RegionController::show' => '?',
    'App\\Controller\\AdminController\\RegionController:delete' => '?',
    'App\\Controller\\AdminController\\RegionController:edit' => '?',
    'App\\Controller\\AdminController\\RegionController:index' => '?',
    'App\\Controller\\AdminController\\RegionController:show' => '?',
]);
